### ISSUE TITLE
A quick question about asynchronous operations

### ISSUE THREAD

**Issue by ikarus-wing** [Funatiq/gossip#1]
Hi gossip developers,

Thanks for the great framework that enables high performance p2p operations. I notice that you provide an API called `all2all_async`. Does it mean that all GPUs can do all2all asynchronously (without having to coordinate with others, like NCCL)?

My next question is: are existing scatter/gather APIs asynchronous (or can they support that)?

**Comment by Funatiq** [comment]
Hi!
Gossip's primitives are executed in phases. The difference between `all2all` and `all2all_async` is that the asynchronous variant does not synchronize all devices between phases, but it needs additional memory for intermediate transfers. The synchronous variant uses the same double buffer for each phase, which necessitates the synchronization. 

Scatter and gather are also asynchronous. They use the same execution scheme as `all2all_async`.

Gossip's transfer plans are designed to execute a phase simultaneously on all devices for maximum throughput, so the coordination of devices is given by the plan. "Asynchronous execution" for gossip means the same as for other asynchronous CUDA calls: the execution on the device(s) is asynchronous to the host, meaning the call may return before the devices finished executing.

That being said, for transfer plans which only have one phase (this is the case for most fully connected topologies) you can use gossip's asynchronous primitives to execute the transfers without coordination between GPUs.

**Comment by ikarus-wing** [comment]
@Funatiq Thank you for your detailed response. Let me confirm a quick point: If I want GPU0 to gather from a tensor address in GPU1, and hope that GPU1 is not interrupted by this gather (i.e., GPU1 does its own works without the need to synchronize and wait until this gather finishes), is this feasible using gossip?

BTW, does gossip supports variable length using gather/scatter? In my case, different GPUs may have different length of addresses.

**Comment by ikarus-wing** [comment]
I encountered another problem. When I try to generate the plan file on my machine for asynchronous gather, I meet the following error. Please correct me if I am doing something wrong.

```
User@scripts # python3 plan_from_topology_asynch.py gather 0
[[8. 1. 2. 1. 0. 0. 0. 2.]
 [1. 8. 1. 2. 0. 0. 2. 0.]
 [2. 1. 8. 2. 0. 1. 0. 0.]
 [1. 2. 2. 8. 1. 0. 0. 0.]
 [0. 0. 0. 1. 8. 2. 2. 1.]
 [0. 0. 1. 0. 2. 8. 1. 2.]
 [0. 2. 0. 0. 2. 1. 8. 1.]
 [2. 0. 0. 0. 1. 2. 1. 8.]]
[[8. 1. 2. 1. 0. 0. 0. 2.]
 [1. 8. 1. 2. 0. 0. 2. 0.]
 [2. 1. 8. 2. 0. 1. 0. 0.]
 [1. 2. 2. 8. 1. 0. 0. 0.]
 [0. 0. 0. 1. 8. 2. 2. 1.]
 [0. 0. 1. 0. 2. 8. 1. 2.]
 [0. 2. 0. 0. 2. 1. 8. 1.]
 [2. 0. 0. 0. 1. 2. 1. 8.]]
main: 0 degree: 6
plan_from_topology_asynch.py:101: RuntimeWarning: divide by zero encountered in true_divide
  lengths = np.where(capacities <= max_capacity, max_capacity / capacities, 1)
topology:
[[8. 1. 2. 1. 0. 0. 0. 2.]
 [1. 8. 1. 2. 0. 0. 2. 0.]
 [2. 1. 8. 2. 0. 1. 0. 0.]
 [1. 2. 2. 8. 1. 0. 0. 0.]
 [0. 0. 0. 1. 8. 2. 2. 1.]
 [0. 0. 1. 0. 2. 8. 1. 2.]
 [0. 2. 0. 0. 2. 1. 8. 1.]
 [2. 0. 0. 0. 1. 2. 1. 8.]]
max links: 2.0
commodities at begin:
[6. 6. 6. 6. 6. 6. 6. 6.]
commodities at end:
[48.  0.  0.  0.  0.  0.  0.  0.]
Creating flow problem for 0 timesteps
Traceback (most recent call last):
  File "plan_from_topology_asynch.py", line 166, in <module>
    in_out_bounds[0] = commodities_in
ValueError: could not broadcast input array from shape (8) into shape (8,1)
```

**Comment by Funatiq** [comment]
I commited a fix to the problem you encountered. It seems like you are using DGX-1 with Volta GPUs. In this case you can also use the plans from [dgx1_opt](https://github.com/Funatiq/gossip/tree/master/plans/dgx1_opt) or [dgx1_opt_1chunk](https://github.com/Funatiq/gossip/tree/master/plans/dgx1_opt_1chunk) for scatter and gather from GPU 0. The former are similar to the plans generated by the script, while the latter perform better for smaller transfer sizes (see [benchmark](https://github.com/Funatiq/gossip/blob/master/benchmark/plots/dgx1_scatter.pdf)).

To answer your previous questions:
* Gossip uses the streams created in its context for all transfers. You can use your on streams for other work which can be executed asynchronously to gossip (except for `all2all` which synchronizes the whole device as mentioned before).
* Gossip's primitives support variable length for different GPUs. You have to provide the sizes per GPU when calling the primitives.

**Comment by ikarus-wing** [comment]
Thank you very much. Let me test it and will give the feedback later.

**Comment by ikarus-wing** [comment]
The bug is fixed now, and I can run the scatter_gather benchmark. 

This is very helpful for me. I have no further question. I will try to incorporate gossip into my project now. Thanks again.
> To answer your previous questions:
> 
> * Gossip uses the streams created in its context for all transfers. You can use your on streams for other work which can be executed asynchronously to gossip (except for `all2all` which synchronizes the whole device as mentioned before).
> * Gossip's primitives support variable length for different GPUs. You have to provide the sizes per GPU when calling the primitives.

And BTW, is there a plan to support distributed training (say 2 machines and each with 8 GPUs)?

**Comment by Funatiq** [comment]
There are currently no efforts to extend gossip to multiple hosts, but it could be combined with CUDA-aware MPI to communicate between hosts.

Good luck with your project!

**Comment by ikarus-wing** [comment]
Okay, I see. 

I will close this issue. Thank you very much.
