### ISSUE TITLE
a quick question about scatter and gather operation

### ISSUE THREAD

**Issue by kingwales1** [Funatiq/gossip#3]
Hi,

Thanks for your great work. I have a quick question in gossip. In your paper, you mention that the unidirectional scheme needs n−1 transfer steps of half size, while the bidirectional one uses ⌊n−1/2⌋ full size transfer steps. What does the half size and full size mean here? Is it the size of chunks? Could you please give a simple example?

**Comment by Funatiq** [comment]
Hi!
I guess you are referring to the ring-based schemes. Full size means all of the data (denoted d_ij in the paper), while half size means half of the data (each d_ij is split into 2 chunks). As noted in the paper, the unidirectional scheme can be used in both directions of a ring at the same time. Hence, half of the data (one chunk of each d_ij) is transferred in each direction and each transfer is only half as long ("half size"). In the bidirectional scheme the data d_ij are not split, instead we choose the direction in which we send the data through the ring.
Does that make it clear?

**Comment by Young768** [comment]
Oh. I got it. Thanks.

**Comment by Young768** [comment]
Hi @Funatiq I have two more questions:

1. what does the "asynchronously" mean? I notice that both gather and scatter are asynchronous.

2. regarding the usage of all_to_all_aync? should the para src and dst pointer exactly the same? since we are going to gather and scatter from all nodes to all nodes.

**Comment by Funatiq** [comment]
1. Please take a look [here](https://github.com/Funatiq/gossip/issues/1#issuecomment-639329431) and [here](https://github.com/Funatiq/gossip/issues/1#issuecomment-640011293), where I explained the asynchronous execution. I will extend the README when I find some time.
2. Don't confuse all-to-all with all-gather. In all-to-all each node gathers different data, especially only a part of its own src array. Therefore src and dst must be different arrays.

**Comment by kingwales1** [comment]
Thanks! @Funatiq

**Comment by kingwales1** [comment]
Hi @Funatiq why do you need sync() api for gather if they are asynchronous?

void sync () const noexcept {
        context->sync_all_streams();
    }

**Comment by Funatiq** [comment]
It's not really needed but rather a convenience. If you want to make sure that host waits until the transfers are finished, you have to synchronize somehow. For example, we use this to get the duration of the transfers in [executor.cuh](https://github.com/Funatiq/gossip/blob/master/executor.cuh).
