### ISSUE TITLE
Questions about the usage of Gather API

### ISSUE THREAD

**Issue by ikarus-wing** [Funatiq/gossip#4]
Hi @Funatiq , 

When I use the gather API, I am confused about its usage:

```
execAsync (
        const std::vector<value_t *>& srcs,
        const std::vector<index_t  >& srcs_lens,
        const std::vector<table_t  >& send_counts,
        value_t * dst,
        const index_t dst_len,
        bool verbose = false
    ) 
```

What is the difference between `srcs_lens` and `send_counts`? If `srcs_lens` refers to the length of the srcs address, why do we need it? Looks like having `send_counts` would be enough for gossip to do the transmission.

**Comment by Funatiq** [comment]
The API and implementation are a little convoluted for scatter and gather. Gather may need some additional space for intermediate buffering and expects to find this space in the `srcs` behind the `send_counts`. Same goes for scatter and `dsts`. Maybe it would be better to use separate buffer arrays like in all_to_all_async? What would you prefer?

**Comment by ikarus-wing** [comment]
> Gather may need some additional space for intermediate buffering and expects to find this space in the `srcs` behind the `send_counts`.

Is there an exact number of how much extra space is needed behind the send_counts? Using separate buffer is acceptable for now. But I just need a number to correctly pre-allocate a buffer that is large enough.

I need the gather API to correctly handle the following example. Suppose we have 4 GPUs, and each of them has a tensor with different size.

```
GPU0: srcs={0,1,2,3}
GPU1: srcs={4,5}
GPU2: srcs={6,7}
GPU3: srcs={8,9}
```

If I launch gather on GPU0 (main_gpu), I expect to get a tensor `dst={0,1,2,3,4,5,6,7,8,9}` on GPU0 after the gather operation. Is this feasible by any chance?

**Comment by ikarus-wing** [comment]
> Maybe it would be better to use separate buffer arrays like in all_to_all_async? What would you prefer?

Sorry, I forgot to answer this. I will prefer using separate buffers like those in all2all_async. It will be more friendly to users. May I ask is there a plan to implement this?

**Comment by Funatiq** [comment]
The required buffer size depends on the transfer plan which takes the connection topology into account. I will add the function to calculate the buffer sizes like in all_to_all_async. I will also change the API to use separate buffers.

**Comment by ikarus-wing** [comment]
Thank you very much. Looking forward to this feature.

**Comment by ikarus-wing** [comment]
BTW, I would appreciate if the Scatter API can be improved too.

**Comment by Funatiq** [comment]
I committed the changes into master (https://github.com/Funatiq/gossip/commit/c7e9ad9e36e2ad9b696cb0616fba35a7cd3e2f59). The APIs for scatter and gather are now similar to all_to_all_async.

**Comment by ikarus-wing** [comment]
Awesome! Will give a test now.

**Comment by ikarus-wing** [comment]
Running the benchmark shows error:

```
<User> gossip # ./execute scatter_gather scripts/scatter_plan.json scripts/gather_plan.json 
RUN: scatter_gather
TIMING: 81.6814 ms (malloc_devices)
TIMING: 9.79558 ms (zero_gpu_buffers)
INFO: 2147483648 bytes (scatter_gather)
TIMING: 3.72838 ms (init_data)
TIMING: 56.0548 ms (multisplit)

Partition Table:
33553989 33562958 33552866 33555233 33552206 33551309 33550824 33556071
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0

Required buffer sizes:
0 33550824 44737030 39147132 0 22368140 0 44735679 

TIMING: -2.60576e-17 ms (malloc_buffers)
CUDA error: invalid resource handle : include/gossip/context.cuh, line 180
```

But the all2all benchmark is fine.

**Comment by Funatiq** [comment]
I am not sure if this fixes your problem, but could you test the branch [issue_4](https://github.com/Funatiq/gossip/tree/issue_4)? On my machine there was no error.

**Comment by ikarus-wing** [comment]
Still does not work. But now comes a new error.
```
<User> gossip # ./execute scatter_gather scripts/scatter_plan.json scripts/gather_plan.json 
RUN: scatter_gather
TIMING: 82.005 ms (malloc_devices)
TIMING: 10.2533 ms (zero_gpu_buffers)
INFO: 2147483648 bytes (scatter_gather)
TIMING: 3.71302 ms (init_data)
TIMING: 56.1306 ms (multisplit)

Partition Table:
33553989 33562958 33552866 33555233 33552206 33551309 33550824 33556071
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0
0 0 0 0 0 0 0 0

Required buffer sizes:
0 33550824 44737030 39147132 0 22368140 0 44735679 

TIMING: 3.37935e+24 ms (malloc_buffers)
CUDA error: invalid resource handle : executor.cuh, line 473
```

**Comment by Funatiq** [comment]
I removed the error checking from context because it's no use to get the line from inside the context sync call. It's probably the same error as before, but now we can better see where it happens. Sadly I still have no idea what is going wrong.

**Comment by ikarus-wing** [comment]
Does it make sense that the error occurs before `scatter.execAsync`? I am confused why it happens since it does not even touch the scatter logic (which you modified).

I tried to insert this two lines [here](https://github.com/Funatiq/gossip/blob/c14747ee3a136db09777273e72babf22a9d8df3e/executor.cuh#L461), before line 473.  
```
context.sync_all_streams();
CUERR
```
And the error is now at line 461. But the CUERR check at line 450 is fine. So does it mean the error is triggered by the following lines?
https://github.com/Funatiq/gossip/blob/c14747ee3a136db09777273e72babf22a9d8df3e/executor.cuh#L455-L460

**Comment by Funatiq** [comment]
I also refactored the executor.cuh to allocate separate buffers for scatter and gather. I don't see how the lines you mentioned could trigger an CUDA error. It could be caused by the sync in line 451, but I see no reason for this behavior.

**Comment by Funatiq** [comment]
I did an complete overhaul of the executor.cuh where I removed most of the hard syncs as they seemed not really necessary. I don't know if and how this relates to your problem, but you can try out the updated master.

**Comment by ikarus-wing** [comment]
Although the scatter_gather benchmark of gossip does not work, fortunately I seem to successfully enable the scatter/gather APIs in my project (using master branch, https://github.com/Funatiq/gossip/commit/c7e9ad9e36e2ad9b696cb0616fba35a7cd3e2f59). 

Not sure what happened in the benchmark though.

**Comment by ikarus-wing** [comment]
Close this for now since we don't see problems when using scatter/gather in our end-to-end system. But I hope the benchmark can also be fixed when the reason has been figured out.

**Comment by ikarus-wing** [comment]
> I don't know if and how this relates to your problem, but you can try out the updated master.

I didn't see this, sorry. The latest master (https://github.com/Funatiq/gossip/commit/760d4b49707f69023e38dddc8b128498feb14495) still has the same problem. But anyway, it is fine for me now...
