### ISSUE TITLE
Linker: multiple definition error caused by implementing non-inline, non-template functions in header

### ISSUE THREAD

**Issue by jdaaph** [Funatiq/gossip#5]
@Funatiq Thanks for the great work!
When using Gossip in multiple c++ source files, at linking I'm seeing the following error:
```
xxx.a: In function `gossip::check(bool, char const*)':
yyy.cpp:(.text+0x18f0): multiple definition of `gossip::check(bool, char const*)'
xxx:yyy.cpp:(.text+0x20): first defined here
```
This is due to the fact that https://github.com/Funatiq/gossip/blob/760d4b49707f69023e38dddc8b128498feb14495/include/gossip/error_checking.hpp#L9 , the non-template, non-inline function is implemented in a header file and across different translation unit (when I include the header in two different cpp source files) source files would have multiple copies of the function. Adding header guards such as `#pragma once` would not help in this case. 

Could you update the repo with __inline__ keyword to that function and hopefully separate the implementation from the declaration in the header files? I see other header files might potentially have the same issue if included in someone else's code. It would be super beneficial if you can separate impl from the headers for other people to use your code in research and work!

There is an excellent discussion here about the similar issue in Stan: https://github.com/stan-dev/stan/issues/1149#issuecomment-64277140

**Comment by Funatiq** [comment]
Hi! Thank you for the remark, you are absolutely right. I just pushed an update for the function (https://github.com/Funatiq/gossip/commit/84ff74f07931c9a5f26fc6aa52896b7e1d53017e).

I think it would be too much to separate the implementations from the headers. I would prefer to stay header-only as much as possible.
